config/routes.rb
Rails.application.routes.draw do

  resources :statuses do 
  	resources :members, only: [:create, :destroy]
  end

  root 'statuses#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :status
  validates :name, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :members
#  validates :status, :color, presence: true
  validates :status, :color, presence: { message: "入力して下さい"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def create
    @status = Status.find(params[:status_id])
    @member = @status.members.create(member_params)
    redirect_to status_path(@status.id)
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to status_path(params[:status_id])
  end

  private

    def member_params
      params[:member].permit(:name)
    end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  before_action :set_status, only: [:show, :edit, :update, :destroy]

  def index
    @statuses = Status.all
  end

  def show
#    @status = Status.find(params[:id]) # del by before_action
  end

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      redirect_to statuses_path
    else
      render 'new'
    end
  end

  def edit
#    @status = Status.find(params[:id]) # del by before_action
  end

  def update
#    @status = Status.find(params[:id]) # del by before_action
    if @status.update(status_params)
      redirect_to statuses_path
    else
      render 'edit'
    end
  end

  def destroy
#    @status = Status.find(params[:id]) # del by before_action
    @status.destroy
    redirect_to statuses_path
  end

  private

    def status_params
      params[:status].permit(:status, :color)
#      params[:status].permit(:color)
    end

    def set_status
      @status = Status.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Statview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>

  <%= link_to "Home", statuses_path %>

  </body>
</html>

app/views/statuses/_form.html.erb
<%= form_for @status do |f| %>

<p>
  <%= f.label :status %><br>
  <%= f.text_field :status %>
  <% if @status.errors.any? %>
  <%= @status.errors.messages[:status][0] %>
  <% end %>
</p>

<p>
  <%= f.label :color %><br>
  <%= f.text_field :color %>
  <% if @status.errors.any? %>
  <%= @status.errors.messages[:color][0] %>
  <% end %>
</p>

<p>
  <%= f.submit %>
</p>

<p>
  ## using partial ##
</p>

<% end %>

app/views/statuses/edit.html.erb
<h1>Edit Status</h1>

<%= render 'form' %>

app/views/statuses/index.html.erb
<h1>Statuses</h1>

<ul>

  <% @statuses.each do |stat| %>
  <li>
    <%= link_to stat.status, status_path(stat.id) %>
    <%= link_to "[Edit]", edit_status_path(stat.id) %>
    <%= link_to "[Delete]", status_path(stat.id), method: :delete, data:  {confirm: "are you sure?" } %></li> 
  <ul>
  <li><%= stat.color %></li>
  </ul>

  <% end %>

</ul>

<p><%= link_to "Add New Status", new_status_path %></p>

<hr>

<style>
    table {
        border-collapse:    collapse;
    }
    td, th {
        padding:    10px;
        border: 2px solid dimgray;
    }
    th {
        background: cornsilk;
    }
</style>
 
<table>
    <tr>
        <th>Aチーム</th>
        <th>Ｂチーム</th>
        <th>Ｃチーム</th>
    </tr>
    <tr>
        <td style="background:#00f;"><font color="#ffffff">alice</td>
        <td style="background:#0f0;">merry</td>
        <td style="background:#f00;">aya</td>
    </tr>
    <tr>
        <td style="background:#00f;"><font color="#ffffff">mima</td>
        <td style="background:#000;"><font color="#ffffff">yumemi</td>
        <td style="background:#444;">eren</td>
    </tr>
</table>

<hr>

app/views/statuses/new.html.erb
<h1>Add New Status</h1>

<%= render 'form' %>

app/views/statuses/show.html.erb
<h1><%= @status.status %></h1>

<ul>

<% @status.members.each do |member| %>
<li>
  <%= member.name %>
  <%= link_to "[Delete]", status_member_path(member.status_id, member.id), method: :delete, data:  {confirm: "are you sure?" } %>
</li> 

<% end %>

<li>
  <%= form_for [@status, @status.members.build] do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
  <% end %>
</ul>